In [7]:
"""
Introduction to Python Matrices and NumPy
"""
import numpy as np

arr1 = np.arange(5)
print(arr1)

arr2 = np.arange(1,20,3)
print(arr2)

lin_spaced_arr = np.linspace(0,100,5, dtype = int)
print(lin_spaced_arr)

char_arr = np.array(['Oss, white belt'])
print(char_arr)
print(char_arr.dtype)

ones = np.ones(5, dtype = int)
print(ones)

rand_arr = np.random.rand(4)
print(rand_arr)

# continue at 2 in C1_W1_Lab_1_introduction_to_numpy_arrays

[0 1 2 3 4]
[ 1  4  7 10 13 16 19]
[  0  25  50  75 100]
['Oss, white belt']
<U15
[1 1 1 1 1]
[0.01159396 0.537145   0.9243192  0.90001025]
