In [6]:
"""
Introduction to Python Matrices and NumPy
"""
import numpy as np

arr1 = np.arange(5)
print(arr1)

arr2 = np.arange(1,20,3)
print(arr2)

lin_spaced_arr = np.linspace(0,100,5, dtype = int)
print(lin_spaced_arr)

char_arr = np.array(['Oss, white belt'])
print(char_arr)
print(char_arr.dtype)

# Continue from 1.4 - More on NumPy arrays

[0 1 2 3 4]
[ 1  4  7 10 13 16 19]
[  0  25  50  75 100]
['Oss, white belt']
<U15
