In [15]:
"""
Introduction to Python Matrices and NumPy
"""
import numpy as np

# Basics
arr1 = np.arange(5)
print(arr1)

arr2 = np.arange(1,20,3)
print(arr2)

lin_spaced_arr = np.linspace(0,100,5, dtype = int)
print(lin_spaced_arr)

char_arr = np.array(['Oss, white belt'])
print(char_arr)
print(char_arr.dtype)

ones = np.ones(5, dtype = int)
print(ones)

rand_arr = np.random.rand(4)
print(rand_arr)
print()

#Multidimensional Arrays
two_D_arr = np.array([[11,12,13],[21,22,23]])
print(two_D_arr)

one_D_arr = np.array([1,2,3,4,5,6,7,8,9,10])
multi_D_arr = np.reshape(one_D_arr, (2,5))
print(multi_D_arr)

print("dimension: " + str(multi_D_arr.ndim) + ", shape: " + str(multi_D_arr.shape) + ", size: " + str(multi_D_arr.size))

multip_arr = np.array([1,2,3]) * np.array([4,5,6])
print (multip_arr)

a1 = np.array([[1,1],
               [2,2]])
a2 = np.array([[3,3],
               [4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

vert_stack = np.hstack((a1,a2))
print(f"horiz:\n{vert_stack}")

[0 1 2 3 4]
[ 1  4  7 10 13 16 19]
[  0  25  50  75 100]
['Oss, white belt']
<U15
[1 1 1 1 1]
[0.12131736 0.76537744 0.21283142 0.81836389]

[[11 12 13]
 [21 22 23]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
dimension: 2, shape: (2, 5), size: 10
[ 4 10 18]
a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]
horiz:
[[1 1 3 3]
 [2 2 4 4]]


In [ ]:
"""
Solving Linear Systems with 2 variables
"""

import numpy as np
import matplotlib.pyplot as plt

# solve a system using matrices
A = np.array([
    [-1, 3],
    [3, 2]
])
b = np.array([7,1])
x = np.linalg.solve(A,b)
print(f"Solution: {x}")

#evaluate determinant
detA = np.linalg.det(A)
print(f"Determinant of A: {detA}")

#solve a system using Elimination Method
A_system = np.hstack((A,b.reshape((2,1))))
print(f"A_system:\n{A_system}")
A_syst_res = A_system.copy()
A_syst_res[1] = 3 * A_syst_res[0] + A_syst_res[1]
print(f"A_system_res:\n{A_syst_res}")
A_syst_res[1]= 1/11 * A_syst_res[1]
print(f"A_system_res:\n{A_syst_res}")

#Graphical Representation of the Solution
def plot_lines(matr):
    x_1 = np.linspace(-10,10,100)
    x_2_line_1 = (matr[0,2] - matr[0,0] * x_1) / matr[0,1]
    x_2_line_2 = (matr[1,2] - matr[1,0] * x_1) / matr[1,1]

    _, ax = plt.subplots(figsize=(10, 10))
    ax.plot(x_1, x_2_line_1, '-', linewidth=2, color='#0075ff',
            label=f'$x_2={-matr[0,0] / matr[0,1]:.2f}x_1 + {matr[0,2] / matr[0,1]:.2f}$')
    ax.plot(x_1, x_2_line_2, '-', linewidth=2, color='#ff7300',
            label=f'$x_2={-matr[1,0] / matr[1,1]:.2f}x_1 + {matr[1,2] / matr[1,1]:.2f}$')

    A = matr[:, 0:-1]
    b = matr[:, -1::].flatten()
    d = np.linalg.det(A)

    if d != 0:
        solution = np.linalg.solve(A,b)
        ax.plot(solution[0], solution[1], '-o', mfc='none',
                markersize=10, markeredgecolor='#ff0000', markeredgewidth=2)
        ax.text(solution[0]-0.25, solution[1]+0.75, f'$(${solution[0]:.0f}$,{solution[1]:.0f})$', fontsize=14)
    ax.tick_params(axis='x', labelsize=14)
    ax.tick_params(axis='y', labelsize=14)
    ax.set_xticks(np.arange(-10, 10))
    ax.set_yticks(np.arange(-10, 10))

    plt.xlabel('$x_1$', size=14)
    plt.ylabel('$x_2$', size=14)
    plt.legend(loc='upper right', fontsize=14)
    plt.axis([-10, 10, -10, 10])

    plt.grid()
    plt.gca().set_aspect("equal")

    plt.show()

plot_lines(A_system)

In [ ]:
"""
Solving Linear Systems with 3 variables
"""
import numpy as np

A = np.array([
    [4, -3, 1],
    [2, 1, 3],
    [-1, 2, -5]
])
b = np.array([-10, 0, 17])

x = np.linalg.solve(A,b)
print(f"solution for the matrix with det {np.linalg.det(A):.2f}: {x}")

AA = np.hstack((A,b.reshape((3,1))))
print(f"matrix AA: \n{AA}")

In [ ]:
"""
Row echelon form
"""
import sympy as sp
import numpy as np
A = np.array([
    [1, 2, 3],
    [3, 4, 7],
    [6, 5, 9]
])
b = np.array([-10, 0, 17])
M = sp.Matrix(np.hstack((A,b.reshape((3,1)))))
print(f"Matrix: \n{np.array(M).astype(np.float64)}")
# np.array(M).astype(np.float64).

M_row_echelon= M.echelon_form()
print(f"row echelon form: \n{np.array(M_row_echelon).astype(np.float64)}")
M_reduced_echelon = M.rref()[0]
print(f"reduced row echelon form: \n{np.array(M_reduced_echelon).astype(np.float64)}")


In [ ]:
"""
Lab: Vector operations
"""
import numpy as np
import matplotlib.pyplot as plt
import time

def plot_vectors(list_v, list_label, list_color):
    _, ax = plt.subplots(figsize=(10, 10))
    ax.tick_params(axis='x', labelsize=14)
    ax.tick_params(axis='y', labelsize=14)
    ax.set_xticks(np.arange(-10, 10))
    ax.set_yticks(np.arange(-10, 10))


    plt.axis([-10, 10, -10, 10])
    for i, v in enumerate(list_v):
        sgn = 0.4 * np.array([[1] if i==0 else [i] for i in np.sign(v)])
        plt.quiver(v[0], v[1], color=list_color[i], angles='xy', scale_units='xy', scale=1)
        ax.text(v[0]-0.2+sgn[0], v[1]-0.2+sgn[1], list_label[i], fontsize=14, color=list_color[i])

    plt.grid()
    plt.gca().set_aspect("equal")
    plt.show()

v = np.array([[1],[3]])
# Scalar multiplication
#plot_vectors([v, 2*v, -2*v], [f"$v$", f"$2v$", f"$-2v$"], ["black", "green", "blue"])

# Sum of vectors
v = np.array([[1],[3]])
w = np.array([[4],[-1]])
#plot_vectors([v, w, v + w], [f"$v$", f"$w$", f"$v + w$"], ["black", "black", "red"])
#plot_vectors([v, w, np.add(v, w)], [f"$v$", f"$w$", f"$v + w$"], ["black", "black", "red"])

# Norm of a Vector
print("Norm of a vector v is", np.linalg.norm(v))

# Dot Product
x = [1, -2, -5]
y = [4, 3, -1]

def dot(x, y):
    s = 0
    for xi, yi in zip(x, y):
        s += xi * yi
    return s

print(f"The dot product of {x}  and {y} is {dot(x, y)}")
print("np.dot(x,y) function returns dot product of x and y:", np.dot(x, y))
print("This line output is a dot product of x and y: ", np.array(x) @ np.array(y))
x = np.array(x)
y = np.array(y)

# Speed of Calculations in Vectorized Form
a = np.random.rand(1000001)
b = np.random.rand(1000001)

tic = time.time()
c = dot(a,b)
toc = time.time()
print(f"\nDot product: {c}")
print ("Time for the loop version:" + str(1000*(toc-tic)) + " ms")

tic = time.time()
c = np.dot(b,a)
toc = time.time()
print("Dot product: ", c)
print ("Time for the vectorized version, np.dot() function: " + str(1000*(toc-tic)) + " ms")

i = np.array([1, 0, 0])
j = np.array([0, 1, 0])
print("The dot product of i and j is", dot(i, j))

In [48]:
"""
Lab: Matrix Multiplication
"""
import numpy as np

A = np.array([[4, 9, 9], [9, 1, 6], [9, 2, 3]])
print("Matrix A (3 by 3):\n", A)

B = np.array([[2, 2], [5, 7], [4, 4]])
print("Matrix B (3 by 2):\n", B)

AB = np.matmul (A,B)
AB_dotP = np.dot(A, B) # broadcasting
print(f"AB with matmul: \n {AB}")
print(f"AB with Dot Product: \n {AB_dotP}")

Matrix A (3 by 3):
 [[4 9 9]
 [9 1 6]
 [9 2 3]]
Matrix B (3 by 2):
 [[2 2]
 [5 7]
 [4 4]]
AB with matmul: 
 [[ 89 107]
 [ 47  49]
 [ 40  44]]
AB with Dot Product: 
 [[ 89 107]
 [ 47  49]
 [ 40  44]]


In [50]:
"""
Linear Transformations
"""
import numpy as np

def T(v):
    w = np.zeros((3,1))
    w[0,0] = 3*v[0,0]
    w[2,0] = -2*v[1,0]

    return w

v = np.array([[3], [5]])
w = T(v)
print("Original vector:\n", v, "\n\n Result of the transformation:\n", w)

def L(v):
    A = np.array([[3,0], [0,0], [0,-2]])
    print("Transformation matrix:\n", A, "\n")
    w = A @ v

    return w

v = np.array([[3], [5]])
w = L(v)

print("Original vector:\n", v, "\n\n Result of the transformation:\n", w)


Original vector:
 [[3]
 [5]] 

 Result of the transformation:
 [[  9.]
 [  0.]
 [-10.]]
Transformation matrix:
 [[ 3  0]
 [ 0  0]
 [ 0 -2]] 

Original vector:
 [[3]
 [5]] 

 Result of the transformation:
 [[  9]
 [  0]
 [-10]]


In [65]:
"""
Assignment: 1-Perceptron NN
"""
import numpy as np
import matplotlib.pyplot as plt
# A function to create a dataset.
from sklearn.datasets import make_regression
# A library for data manipulation and analysis.
import pandas as pd
# Some functions defined specifically for this notebook.
import w3_tools
# Output of plotting commands is displayed inline within the Jupyter notebook.
%matplotlib inline

# Set a seed so that the results are consistent.
np.random.seed(3)

m = 30

X, Y = make_regression(n_samples=m, n_features=1, noise=20, random_state=1)

X = X.reshape((1, m))
Y = Y.reshape((1, m))

print('Training dataset X:')
print(X)
print('Training dataset Y')
print(Y)

plt.scatter(X,  Y, c="black")

plt.xlabel("$x$")
plt.ylabel("$y$")

### START CODE HERE ### (~ 3 lines of code)
# Shape of variable X.
shape_X = X.shape
# Shape of variable Y.
shape_Y = Y.shape
# Training set size.
m = X.size
### END CODE HERE ###

print ('The shape of X: ' + str(shape_X))
print ('The shape of Y: ' + str(shape_Y))
print ('I have m = %d training examples!' % (m))

def layer_sizes(X, Y):
    """
    Arguments:
    X -- input dataset of shape (input size, number of examples)
    Y -- labels of shape (output size, number of examples)

    Returns:
    n_x -- the size of the input layer
    n_y -- the size of the output layer
    """
    ### START CODE HERE ### (~ 2 lines of code)
    # Size of input layer.
    n_x = X.shape[0]
    # Size of output layer.
    n_y = Y.shape[0]
    ### END CODE HERE ###
    return (n_x, n_y)

(n_x, n_y) = layer_sizes(X, Y)
print("The size of the input layer is: n_x = " + str(n_x))
print("The size of the output layer is: n_y = " + str(n_y))

def initialize_parameters(n_x, n_y):
    """
    Returns:
    params -- python dictionary containing your parameters:
                    W -- weight matrix of shape (n_y, n_x)
                    b -- bias value set as a vector of shape (n_y, 1)
    """

    ### START CODE HERE ### (~ 2 lines of code)
    W = np.random.randn(n_x,n_y) * 0.01
    b = np.zeros((n_x,n_y))
    ### END CODE HERE ###

    assert (W.shape == (n_y, n_x))
    assert (b.shape == (n_y, 1))

    parameters = {"W": W,
                  "b": b}

    return parameters

parameters = initialize_parameters(n_x, n_y)
print("W = " + str(parameters["W"]))
print("b = " + str(parameters["b"]))

def forward_propagation(X, parameters):
    """
    Argument:
    X -- input data of size (n_x, m)
    parameters -- python dictionary containing your parameters (output of initialization function)

    Returns:
    Y_hat -- The output
    """
    # Retrieve each parameter from the dictionary "parameters".
    ### START CODE HERE ### (~ 2 lines of code)
    W = parameters["W"]
    b = parameters["b"]
    ### END CODE HERE ###

    # Implement Forward Propagation to calculate Z.
    ### START CODE HERE ### (~ 2 lines of code)
    Z = W * X + b
    Y_hat = Z
    ### END CODE HERE ###

    assert(Y_hat.shape == (n_x, X.shape[1]))

    return Y_hat

Y_hat = forward_propagation(X, parameters)

print(f"\nY^:\n{Y_hat}")

def compute_cost(Y_hat, Y):
    """
    Computes the cost function as a sum of squares

    Arguments:
    Y_hat -- The output of the neural network of shape (n_y, number of examples)
    Y -- "true" labels vector of shape (n_y, number of examples)

    Returns:
    cost -- sum of squares scaled by 1/(2*number of examples)

    """
    # Number of examples.
    m = Y.shape[1]

    # Compute the cost function.
    cost = np.sum((Y_hat - Y)**2)/(2*m)

    return cost

print("cost = " + str(compute_cost(Y_hat, Y)))

def nn_model(X, Y, num_iterations=10, print_cost=False):
    """
    Arguments:
    X -- dataset of shape (n_x, number of examples)
    Y -- labels of shape (n_y, number of examples)
    num_iterations -- number of iterations in the loop
    print_cost -- if True, print the cost every iteration

    Returns:
    parameters -- parameters learnt by the model. They can then be used to make predictions.
    """

    n_x = layer_sizes(X, Y)[0]
    n_y = layer_sizes(X, Y)[1]

    # Initialize parameters
    ### START CODE HERE ### (~ 1 line of code)
    parameters = initialize_parameters(n_x, n_y)
    ### END CODE HERE ###

    # Loop
    for i in range(0, num_iterations):

        ### START CODE HERE ### (~ 2 lines of code)
        # Forward propagation. Inputs: "X, parameters". Outputs: "Y_hat".
        Y_hat = None

        # Cost function. Inputs: "Y_hat, Y". Outputs: "cost".
        cost = None
        ### END CODE HERE ###


        # Parameters update.
        parameters = w3_tools.train_nn(parameters, Y_hat, X, Y)

        # Print the cost every iteration.
        if print_cost:
            print ("Cost after iteration %i: %f" %(i, cost))

    return parameters

parameters = nn_model(X, Y, num_iterations=15, print_cost=True)
print("W = " + str(parameters["W"]))
print("b = " + str(parameters["b"]))

W_simple = parameters["W"]
b_simple = parameters["b"]

X_pred = np.array([-0.95, 0.2, 1.5])

fig, ax = plt.subplots()
plt.scatter(X, Y, color = "black")

plt.xlabel("$x$")
plt.ylabel("$y$")

X_line = np.arange(np.min(X[0,:]),np.max(X[0,:])*1.1, 0.1)
ax.plot(X_line, W_simple[0,0] * X_line + b_simple[0,0], "r")
ax.plot(X_pred, W_simple[0,0] * X_pred + b_simple[0,0], "bo")
plt.plot()
plt.show()

ModuleNotFoundError: No module named 'w3_tools'