In [15]:
"""
Introduction to Python Matrices and NumPy
"""
import numpy as np

# Basics
arr1 = np.arange(5)
print(arr1)

arr2 = np.arange(1,20,3)
print(arr2)

lin_spaced_arr = np.linspace(0,100,5, dtype = int)
print(lin_spaced_arr)

char_arr = np.array(['Oss, white belt'])
print(char_arr)
print(char_arr.dtype)

ones = np.ones(5, dtype = int)
print(ones)

rand_arr = np.random.rand(4)
print(rand_arr)
print()

#Multidimensional Arrays
two_D_arr = np.array([[11,12,13],[21,22,23]])
print(two_D_arr)

one_D_arr = np.array([1,2,3,4,5,6,7,8,9,10])
multi_D_arr = np.reshape(one_D_arr, (2,5))
print(multi_D_arr)

print("dimension: " + str(multi_D_arr.ndim) + ", shape: " + str(multi_D_arr.shape) + ", size: " + str(multi_D_arr.size))

multip_arr = np.array([1,2,3]) * np.array([4,5,6])
print (multip_arr)

a1 = np.array([[1,1],
               [2,2]])
a2 = np.array([[3,3],
               [4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

vert_stack = np.hstack((a1,a2))
print(f"horiz:\n{vert_stack}")

[0 1 2 3 4]
[ 1  4  7 10 13 16 19]
[  0  25  50  75 100]
['Oss, white belt']
<U15
[1 1 1 1 1]
[0.12131736 0.76537744 0.21283142 0.81836389]

[[11 12 13]
 [21 22 23]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
dimension: 2, shape: (2, 5), size: 10
[ 4 10 18]
a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]
horiz:
[[1 1 3 3]
 [2 2 4 4]]


In [22]:
"""
Determinant of a matrix
"""
import numpy as np

arr1 = np.array([[6,1],
                 [0,3]])
print(f"determinant of arr1 is: {np.linalg.det(arr1)}")

vect1 = np.array([1,1])
print(f"vect1:\n{vect1}")
vect2 = arr1.dot(vect1)
print(f"arr1 * vect1 = \n{vect2}")

determinant of arr1 is: 17.999999999999996
vect1:
[1 1]
arr1 * vect1 = 
[7 3]
